local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

production_local:
  service: Disk
  root: /data/storage

object_store:
  service: S3
  access_key_id: <%= ENV["OBJECT_STORAGE_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["OBJECT_STORAGE_SECRET_ACCESS_KEY"] %>
  region: <%= ENV.fetch("OBJECT_STORAGE_REGION", "auto") %>
  bucket: <%= ENV["OBJECT_STORAGE_BUCKET"] %>
  endpoint: <%= ENV["OBJECT_STORAGE_ENDPOINT"] %>
  force_path_style: <%= ENV.fetch("OBJECT_STORAGE_FORCE_PATH_STYLE", "true") %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
